package com.integraObra.integraobra_api_rest.dto;

import com.integraObra.integraobra_api_rest.models.Product;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

public class ProductResponseDTO {
    private Long id;
    private String name;
    private String cardImageUrl;
    private String sku;
    private int stock;
    private boolean available;
    private String description;
    private List<String> tags;
    private List<String> categories;
    private BigDecimal salePrice;
    private BigDecimal rentPrice;
    private boolean isForRent;
    private boolean isForSale;
    private boolean priceVisibleForRent;
    private boolean priceVisibleForSale;
    private LocalDateTime creationDate;

    public ProductResponseDTO() {
    }

    public ProductResponseDTO(Long id, String name, String cardImageUrl, String sku, int stock, boolean available, String description, List<String> tags, List<String> categories, BigDecimal salePrice, BigDecimal rentPrice, boolean isForRent, boolean isForSale, boolean priceVisibleForRent, boolean priceVisibleForSale, LocalDateTime creationDate) {
        this.id = id;
        this.name = name;
        this.cardImageUrl = cardImageUrl;
        this.sku = sku;
        this.stock = stock;
        this.available = available;
        this.description = description;
        this.tags = tags;
        this.categories = categories;
        this.salePrice = salePrice;
        this.rentPrice = rentPrice;
        this.isForRent = isForRent;
        this.isForSale = isForSale;
        this.priceVisibleForRent = priceVisibleForRent;
        this.priceVisibleForSale = priceVisibleForSale;
        this.creationDate = creationDate;
    }

    public static ProductResponseDTO fromEntity(Product p) {
        if (p == null) return null;
        return new ProductResponseDTO(
                p.getId(),
                p.getName(),
                p.getCardImageUrl(),
                p.getSku(),
                p.getStock(),
                // Product boolean getters generated by Lombok are isXxx() for primitives
                p.isAvailable(),
                p.getDescription(),
                p.getTags(),
                null, // categories: null here, populate if you have category mapping
                p.getSalePrice(),
                p.getRentPrice(),
                p.isForRent(),
                p.isForSale(),
                p.isPriceVisibleForRent(),
                p.isPriceVisibleForSale(),
                p.getCreationDate()
        );
    }

    public Long getId() { return id; }
    public String getName() { return name; }
    public String getCardImageUrl() { return cardImageUrl; }
    public String getSku() { return sku; }
    public int getStock() { return stock; }
    public boolean isAvailable() { return available; }
    public String getDescription() { return description; }
    public List<String> getTags() { return tags; }
    public List<String> getCategories() { return categories; }
    public BigDecimal getSalePrice() { return salePrice; }
    public BigDecimal getRentPrice() { return rentPrice; }
    public boolean isForRent() { return isForRent; }
    public boolean isForSale() { return isForSale; }
    public boolean isPriceVisibleForRent() { return priceVisibleForRent; }
    public boolean isPriceVisibleForSale() { return priceVisibleForSale; }
    public LocalDateTime getCreationDate() { return creationDate; }
}
